version: '3.4'

services:
    rsp-app:
        container_name: rsp-app
        build:
            context: .
        ports:
            - "80:80"
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html
        volumes:
            - ./www:/var/www/html
            - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
    
    rsp-db:
        container_name: rsp-db
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            # We will use named volumes
            - rsp-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
    
    rsp-adminer:
        container_name: rsp-admin
        image: adminer
        ports:
            - 8888:8080

volumes:
    rsp-data:
